<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'JamonDigital\\RteConfig\\' => array($typo3InstallDir . 'typo3conf/ext/rte_config/Classes'),
    'Jamondigital\\JdOgmeta\\' => array($typo3InstallDir . 'typo3conf/ext/jd_ogmeta/Classes'),
    'T3\\Dce\\' => array($typo3InstallDir . 'typo3conf/ext/dce/Classes'),
);
