<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rte_config"
 *
 * Auto generated by Extension Builder 2017-10-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'RTE Configuration',
    'description' => 'Configuration for RTE',
    'category' => 'plugin',
    'author' => 'Marcel Stadelmann',
    'author_email' => 'marcel@jamon.digital',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
